### ISSUE TITLE
Thunderbird eMail needs ports 25, 110, 995 in addition

### ISSUE THREAD

**Issue by peter-hb-1955** [mindfuckup/Scripts#17]
Hello,
this firewall is exactly what I looked for, great. In order to use Mozilla Thunderbird for eMail I had to add the following 3 lines:

$IP46TABLES -A OUTPUT -p tcp --dport 25 -m conntrack --ctstate NEW -j ACCEPT -m comment --comment "SMTP_Thunderbird"

$IP46TABLES -A OUTPUT -p tcp --dport 110 -m conntrack --ctstate NEW -j ACCEPT -m comment --comment "POP3_Thunderbird"

$IP46TABLES -A OUTPUT -p tcp --dport 995 -m conntrack --ctstate NEW -j ACCEPT -m comment --comment "POP3S_Thunderbird"

May be You would like to add them too.
1K Thanks and Best Regards
Peter

**Comment by mindfuckup** [comment]
Hi Peter

Thanks! I'm happy you can use it.

Personally, I don't use this script anymore. I switched to `nftables` for my firewall.

I added the POP3S to the firewall script, thanks for your input.

I did not add SMTP, because a mail client should not send mails to mailservers using this port. Port 25 is used by mailservers for accepting mails for their own domain. A mail client should use the submission port that requires authentication on the mailserver and is used to send mail to external domains.

I did also not add POP3, since this does not use TLS and should therefore not be used.

Anyways, thanks for your input.

Best,
Emanuel
